/**
 * Approving a pending request: the one place a person's yes becomes a schema change.
 *
 * The first attempt at this said yes to every question the oracle asked and was reverted; three
 * reviews found the same class of failure through different doors. So nothing here says a blanket
 * yes. The change is regenerated by **replaying** the decisions the filing boot took — a question it
 * did not record is refused; the live counts are measured again and must fingerprint to what the
 * person was shown; and the apply's confirmers agree only to the exact findings and operations that
 * were approved, declining anything else the oracle turns up on the way.
 *
 * The decision is recorded before the apply. Once a person has clicked, that is a fact; a crash
 * after it leaves `approved` with no `applied`, which the trail shows as it is.
 */

import { converge, describeChange } from '#convergence';

import { hashFindings, measureRequest } from './measure.ts';
import { decisionsOf, unclassifiedOf } from './requests.ts';
import { buildApprovalSchema } from './schema/index.ts';
import { findOpenRequests, recordEvent } from './store.ts';

import type {
	DataLossFinding,
	DecisionResolution,
	Operation,
	RecordedDecision,
	Resolver,
	SchemaDecision,
} from '#convergence';
import type { GlazeContext } from '../app/context.ts';
import type { ApprovalDb, OpenRequest } from './store.ts';
import type { Table } from 'drizzle-orm';

/** Why an approval could not go ahead. Every one of these leaves the database as it was. */
export type ApprovalRefusal =
	/** Somebody decided this request before this approval got its turn. */
	| { readonly reason: 'already_decided' }
	/** The counts moved since the person looked; the fresh measurement is returned to show them. */
	| {
			readonly reason: 'counts_moved';
			readonly findings: readonly DataLossFinding[];
			readonly findingsHash: string;
	  }
	/** The schema no longer produces this change; the next boot reconciles the request. */
	| { readonly reason: 'schema_moved'; readonly detail: string }
	/** Generating the change asked a question the filing boot did not record. */
	| { readonly reason: 'unrecorded_decision'; readonly detail: string };

/** What approving did. */
export type ApprovalOutcome =
	| {
			readonly outcome: 'applied';
			readonly statements: readonly string[];
			readonly migration: string;
	  }
	| { readonly outcome: 'apply_failed'; readonly detail: string }
	| { readonly outcome: 'refused'; readonly refusal: ApprovalRefusal };

/**
 * The identity of a decision, so a recorded answer can be matched to the question asked again.
 *
 * @param decision - The decision.
 * @returns A key over its type, kind and target.
 */
function decisionKey(decision: SchemaDecision): string {
	return [decision.type, decision.targetKind, ...decision.target].join('\0');
}

/**
 * A resolver that answers every question exactly as the filing boot did, and refuses any it did not
 * see. An unattended boot answers `create` to a rename question; the approval must regenerate that
 * same change, not quietly a different one.
 *
 * @param recorded - The decisions recorded on the request.
 * @returns The resolver.
 */
export function replayDecisions(recorded: readonly RecordedDecision[]): Resolver {
	const answers = new Map(
		recorded.map(({ decision, resolution }) => [decisionKey(decision), resolution]),
	);
	return (decision): DecisionResolution =>
		answers.get(decisionKey(decision)) ?? { action: 'reject' };
}

/**
 * The identity of a finding for matching what was approved against what the apply asks about: the
 * change, what was found and how many rows.
 *
 * @param finding - The finding.
 * @returns A key.
 */
function findingKey(finding: DataLossFinding): string {
	return hashFindings([finding]);
}

/**
 * The identity of an operation for matching what was approved against what the apply asks about.
 *
 * @param operation - The operation.
 * @returns A key.
 */
function operationKey(operation: Operation): string {
	return [
		operation.entityType,
		operation.op,
		operation.schema,
		operation.table ?? '',
		operation.name,
	].join('\0');
}

/** Approvals in this process run one at a time: two at once would race on the migration directory. */
let queue: Promise<unknown> = Promise.resolve();

/**
 * Approves an open request as a person: verify the schema still produces the same change, measure it
 * again against what the person saw, record the decision, apply with confirmers that agree only to
 * what was approved, and record the outcome. Approvals take turns, and each begins by checking the
 * request is still open, so two clicks on one request end as one decision and one "already decided".
 *
 * @param context - The Glaze context.
 * @param open - The open request.
 * @param seen - The fingerprint of the findings the person was shown.
 * @param actorId - The account approving.
 * @returns What happened.
 */
export function approveRequest(
	context: GlazeContext,
	open: OpenRequest,
	seen: string,
	actorId: string,
): Promise<ApprovalOutcome> {
	const turn = queue.then(() => approveInTurn(context, open, seen, actorId));
	queue = turn.catch(() => undefined);
	return turn;
}

/**
 * One approval, with the queue's turn held.
 *
 * @param context - The Glaze context.
 * @param open - The open request.
 * @param seen - The fingerprint of the findings the person was shown.
 * @param actorId - The account approving.
 * @returns What happened.
 */
async function approveInTurn(
	context: GlazeContext,
	open: OpenRequest,
	seen: string,
	actorId: string,
): Promise<ApprovalOutcome> {
	const { db, config } = context;
	const events = buildApprovalSchema(config.dialect).approvalEvents as Table;
	const stillOpen = await findOpenRequests(db.db as ApprovalDb, events);
	if (!stillOpen.some((request) => request.requestId === open.requestId)) {
		return { outcome: 'refused', refusal: { reason: 'already_decided' } };
	}
	if (!config.schema) {
		return {
			outcome: 'refused',
			refusal: { reason: 'schema_moved', detail: 'no schema is configured' },
		};
	}
	const base = {
		db,
		dialect: config.dialect,
		schema: config.schema,
		out: config.migrations.path,
		resolve: replayDecisions(decisionsOf(open)),
	};

	// 1. The schema must still produce exactly this change. A dry run: nothing is applied here, not
	// even an additive change the schema might carry instead — an approval applies what was approved
	// and nothing else.
	const verified = await converge({ ...base, dryRun: true });
	if (verified.status === 'rejected') {
		return {
			outcome: 'refused',
			refusal: {
				reason: 'unrecorded_decision',
				detail: `generating the change asks about ${verified.decision.target.join('.')}, which was not answered when the request was filed`,
			},
		};
	}
	if (verified.status !== 'pending' || verified.changeHash !== open.changeHash) {
		const why =
			verified.status === 'pending'
				? 'the schema now produces a different change'
				: verified.status === 'no_changes'
					? 'the schema no longer produces any change'
					: `the schema no longer produces this change (${verified.status})`;
		return {
			outcome: 'refused',
			refusal: { reason: 'schema_moved', detail: `${why}; the next boot reconciles the request` },
		};
	}

	// 2. The counts must be the ones the person saw.
	const measured = await measureRequest((sql) => db.raw(sql), config.dialect, open);
	if (measured.findingsHash !== seen) {
		return { outcome: 'refused', refusal: { reason: 'counts_moved', ...measured } };
	}

	// 3. The decision is a fact from here on.
	await db.queryTransaction((tx) =>
		recordEvent(tx as ApprovalDb, events, {
			requestId: open.requestId,
			type: 'approved',
			actorId,
			actorKind: 'user',
			payload: { findings: measured.findings, findingsHash: measured.findingsHash },
		}),
	);

	// 4. Apply, agreeing only to what was approved.
	const approvedFindings = new Set(measured.findings.map(findingKey));
	const approvedOperations = new Set(unclassifiedOf(open).map(operationKey));
	const applied = await converge({
		...base,
		audit: false,
		confirmDrop: (finding) => approvedFindings.has(findingKey(finding)),
		confirmUnclassified: (operation) => approvedOperations.has(operationKey(operation)),
		// A table vanishing that the classifier did not decide is unexpected, approved or not.
		confirmLoss: () => false,
	});

	// 5. Record the outcome.
	if (applied.status === 'applied') {
		await db.queryTransaction((tx) =>
			recordEvent(tx as ApprovalDb, events, {
				requestId: open.requestId,
				type: 'applied',
				actorId,
				actorKind: 'user',
				payload: { statements: applied.statements, migration: applied.migration },
			}),
		);
		return { outcome: 'applied', statements: applied.statements, migration: applied.migration };
	}
	const detail = describeFailure(applied);
	await db.queryTransaction((tx) =>
		recordEvent(tx as ApprovalDb, events, {
			requestId: open.requestId,
			type: 'apply_failed',
			actorKind: 'system',
			payload: { status: applied.status, detail },
		}),
	);
	return { outcome: 'apply_failed', detail };
}

/**
 * Says why an apply did not go through, in one line.
 *
 * @param result - A converge result other than `applied`.
 * @returns The detail.
 */
function describeFailure(result: Awaited<ReturnType<typeof converge>>): string {
	switch (result.status) {
		case 'drop_declined':
		case 'unsafe_change':
			return `the change measured differently at apply time (${result.findings.map((finding) => `${describeChange(finding.change)}: ${finding.code}`).join('; ')})`;
		case 'unclassified_change':
			return 'the change carries an operation that was not part of what was approved';
		case 'data_loss_declined':
		case 'unexpected_data_loss':
			return `applying would lose rows nobody decided on (${result.losses.map((loss) => loss.table).join(', ')})`;
		case 'rejected':
			return `generating the change asked about ${result.decision.target.join('.')}, which was not answered when the request was filed`;
		case 'error':
			return result.detail ? `${result.code}: ${result.detail}` : result.code;
		case 'no_changes':
			return 'the schema no longer produces this change';
		default:
			return result.status;
	}
}
