// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	schemas: {
		'no-content': {
			/**
			 * D​e​f​i​n​e​ ​y​o​u​r​ ​c​o​n​t​e​n​t​ ​s​t​r​u​c​t​u​r​e
			 */
			title: string
			/**
			 * A​ ​s​c​h​e​m​a​ ​i​s​ ​l​i​k​e​ ​a​ ​f​o​r​m​ ​t​e​m​p​l​a​t​e​ ​—​ ​i​t​ ​s​e​t​s​ ​t​h​e​ ​f​i​e​l​d​s​ ​t​h​a​t​ ​e​v​e​r​y​ ​e​n​t​r​y​ ​o​f​ ​t​h​a​t​ ​t​y​p​e​ ​w​i​l​l​ ​h​a​v​e​.​ ​F​o​r​ ​e​x​a​m​p​l​e​,​ ​a​ ​"​P​o​s​t​s​"​ ​s​c​h​e​m​a​ ​m​i​g​h​t​ ​n​e​e​d​ ​a​ ​t​i​t​l​e​,​ ​a​ ​b​o​d​y​,​ ​a​n​d​ ​a​ ​p​u​b​l​i​s​h​ ​d​a​t​e​.
			 */
			body: string
		}
	}
}

export type TranslationFunctions = {
	schemas: {
		'no-content': {
			/**
			 * Define your content structure
			 */
			title: () => LocalizedString
			/**
			 * A schema is like a form template — it sets the fields that every entry of that type will have. For example, a "Posts" schema might need a title, a body, and a publish date.
			 */
			body: () => LocalizedString
		}
	}
}

export type Formatters = {}
